### ISSUE TITLE
_interopRequireDefault is not a function (it is Object)

### ISSUE THREAD

**Issue by Bardiamist** [launchdarkly/js-core#845]
`@launchdarkly/react-native-client-sdk` doesn't work with React Native 0.79

```
TypeError: _interopRequireDefault is not a function (it is Object), js engine: hermes
Cannot read property 'ReactNativeLDClient' of undefined
```

Need to adjust imports https://reactnative.dev/blog/2025/04/08/react-native-0.79#internal-modules-updated-to-export-syntax
