### ISSUE TITLE
Cannot find module '/home/runner/work/js-core/js-core/node_modules/tslib/tslib.es6.js'

### ISSUE THREAD

**Issue by cullenn** [launchdarkly/js-core#1291]
**Describe the bug**
The ESM build of @launchdarkly/cloudflare-server-sdk@2.7.19 references tslib via an absolute path from the LaunchDarkly CI environment, causing module resolution to fail for all consumers:

```
 Cannot find module '/home/runner/work/js-core/js-core/node_modules/tslib/tslib.es6.js'
 imported from .../node_modules/@launchdarkly/cloudflare-server-sdk/dist/esm/index.js
```
**To reproduce**
 1. Install @launchdarkly/cloudflare-server-sdk@2.7.19
 2. Run any test or import from the ESM bundle
 3. Module resolution fails with the above error

**Expected behavior**
`tslib` should be bundled or referenced as a bare/relative specifier, not an absolute CI path.

**Logs**
See above

**SDK version**
2.7.19

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
Any, the absolute path is baked into the published artifact

**Additional context**
I think it was introduced by #1288 (https://github.com/launchdarkly/js-core/pull/1288) which switched from rollup-plugin-esbuild to @rollup/plugin-typescript. The TypeScript plugin appears to have resolved tslib to an absolute path in the CI environment rather than bundling it.

**Comment by joker23** [comment]
Hi @cullenn - thank you for the report and detailed description.

It looks like I missed some nuances when trying to consolidate our build tooling. Should be able to push a patch in later today.

**Comment by joker23** [comment]
@cullenn we've just published `@launchdarkly/cloudflare-server-sdk@2.7.20` with the fixes to this issue.

**Comment by cullenn** [comment]
Grabbed it & it's running perfectly, ty!
